### ISSUE TITLE
SequelizeBaseError: ER_TOO_LONG_KEY: Specified key was too long

### ISSUE THREAD

**Issue by ARGHtur** [SteveMcGrath/DoFler#14]
I apologize beforehand if this has nothing to do with you code...
I'm new to this and very much stuck right now so I'm reaching out to you.

I followed your install instructions and believe that every thing was done correctly all the way, but now when I try to execute the script all i get is errors that indicate that I have a mysql problem?
When starting the script all I get is this:
root@kali:/opt/dofler# ./server.js 
NGrep: Instantiating ngrep process.
TShark: Instantiating tshark process.
Ettercap: Instantiating dsniff process.
Application Web Server is listening on *:3000
TShark: (stderr): Running as user "root" and group "root". This could be dangerous. 
Unhandled rejection SequelizeBaseError: ER_ACCESS_DENIED_ERROR: Access denied for user 'dofler'@'localhost' (using password: YES)
    at Handshake._callback (/opt/dofler/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:83:20)
    at Handshake.Sequence.end (/opt/dofler/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Handshake.ErrorPacket (/opt/dofler/node_modules/mysql/lib/protocol/sequences/Handshake.js:105:8)
    at Protocol._parsePacket (/opt/dofler/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/opt/dofler/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/opt/dofler/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/dofler/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

and that just loops again and again... the website on 127.0.0.1:3000 seems to work but no data is showing and I think that's because of the access denied error...

So my question is does the dofler user in mysql need a specific password? or am I missing something? some prerequisite maybe? 
I have installed this on a Ubuntu desktop as well and I get the same result/error...
Hope that you or anyone? can help or point me in the right direction...
Thanks
- Artur

**Comment by SteveMcGrath** [comment]
have you setup a config file and modified it to properly talk to your database?

**Comment by ARGHtur** [comment]
I think so? I have configured a production.json file that i copied from the default.json file.
In my file I kept the default "Database": {"uri": "mysql://dofler:dofler@localhost/dofler"}
And the values look to be the same as I used to create the db? 
I followed your instructions :-)

**Comment by SteveMcGrath** [comment]
so the username and password are both "dofler", the database name is "dofler" and mysql is on the same host?

**Comment by ARGHtur** [comment]
Yep... I just figured that out :-) the db user had a wrong password..
Thanks.. now I get past the "access denied" part but get a Unhandled rejection SequelizeBaseError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
any advice?

**Comment by SteveMcGrath** [comment]
can you post the full stacktrace?

**Comment by ARGHtur** [comment]
root@kali:/opt/dofler# ./server.js 
NGrep: Instantiating ngrep process.
TShark: Instantiating tshark process.
Ettercap: Instantiating dsniff process.
Application Web Server is listening on *:3000
TShark: (stderr): Running as user "root" and group "root". This could be dangerous. 
NGrep: (stderr): wlan0mon: no IPv4 address assigned: Cannot assign requested address 
Unhandled rejection SequelizeBaseError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
    at Query.formatError (/opt/dofler/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/opt/dofler/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/opt/dofler/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/opt/dofler/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
    at Protocol._parsePacket (/opt/dofler/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/opt/dofler/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/opt/dofler/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/dofler/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

TShark: (stderr): tshark: Lua: Error during loading:  [string "/usr/share/wireshark/init.lua"]:44: dofile has been disabled due to running Wireshark as superuser. See https://wiki.wireshark.org/CaptureSetup/CapturePrivileges for help in running Wireshark as an unprivileged user. 
TShark: (stderr): Capturing on 'wlan0mon' 
TShark: (stderr): File: - 
TShark: Starting to process packet data.
TShark: Initiating Checkpoint for Fri Apr 21 2017 05:38:00 GMT-0400 (EDT)
TShark: Initiating Checkpoint for Fri Apr 21 2017 05:39:00 GMT-0400 (EDT)
TShark: Initiating Checkpoint for Fri Apr 21 2017 05:40:00 GMT-0400 (EDT)
TShark: Initiating Checkpoint for Fri Apr 21 2017 05:41:00 GMT-0400 (EDT)

**Comment by SteveMcGrath** [comment]
hmm, can you drop the db and make the following changes?

https://github.com/SteveMcGrath/DoFler/blob/master/lib/models.js#L42

replace "Sequelize.STRING" to "Sequelize.STRING(190)"

**Comment by ARGHtur** [comment]
thanks that did it! no errors when starting :-)
