### ISSUE TITLE
Since changes to package deps you need to install mysql2

### ISSUE THREAD

**Issue by TheGroundZero** [SteveMcGrath/DoFler#24]
Since 19fcc29 you need to install the mysql2 node package instead of mysql

To reproduce:

1. Install v5 prior to commit 19fcc29 following the instructions in the README
2. Run DoFler without problems
3. Pull changes to packe.json from commit 19fcc29
4. Run DoFler (`./server.js`)

````
# ./server.js 
/opt/DoFler/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install mysql2 package manually
    at ConnectionManager._loadDialectModule (/opt/DoFler/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/opt/DoFler/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:28:21)
    at new MysqlDialect (/opt/DoFler/node_modules/sequelize/lib/dialects/mysql/index.js:14:30)
    at new Sequelize (/opt/DoFler/node_modules/sequelize/lib/sequelize.js:320:20)
    at Object.<anonymous> (/opt/DoFler/lib/models.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/opt/DoFler/lib/web.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/opt/DoFler/server.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
````

5. Install mysql2

````
# npm install mysql2
+ mysql2@1.6.5
added 10 packages from 11 contributors and audited 363 packages in 2.166s
found 12 vulnerabilities (11 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

# ./server.js 
Driftnet: Started child thread
NGrep: Instantiating ngrep process.
TShark: Instantiating tshark process.
Ettercap: Instantiating dsniff process.
Application Web Server is listening on *:3000
````

I suggest checking if any other dependencies have changed and updating the README to reflect this change.

**Comment by TheGroundZero** [comment]
After doing an `npm install ./` using the new package.json and having installed mysql2, a new error seems to appear once you open the webpage

**Comment by SteveMcGrath** [comment]
yay JS dependency madness.  updated the Sequelize version because of a vuln.  What I want to do is get all of this baked into a docker image that autobuilds
