### ISSUE TITLE
Problem when i start the parsers from the web interface

### ISSUE THREAD

**Issue by madmantm** [SteveMcGrath/DoFler#6]
sudo /usr/local/bin/dofler
Bottle v0.12.8 server starting up (using PasteServer())...
Listening on http://127.0.0.1:8080/
Hit Ctrl-C to quit.

serving on http://127.0.0.1:8080
127.0.0.1 - - [12/Feb/2015:09:39:58 -0700] "POST /ui/settings/services HTTP/1.1" 200 4668 "http://127.0.0.1:8080/ui/settings/services" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0"
127.0.0.1 - - [12/Feb/2015:09:39:58 -0700] "POST /post/login HTTP/1.1" 200 0 "-" "python-requests/1.2.3 CPython/2.7.5+ Linux/3.11.0-12-generic"
Process driftnet:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/dofler/parsers/base.py", line 37, in run
    self.realtime_process()
  File "/usr/local/lib/python2.7/dist-packages/dofler/parsers/base.py", line 54, in realtime_process
    self.p = pexpect.spawn(self.command)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/__init__.py", line 493, in __init__
    fd = sys.__stdin__.fileno()
ValueError: I/O operation on closed file

Help! :)

**Comment by SteveMcGrath** [comment]
is driftnet, ettercap, and tshark installed?

**Comment by madmantm** [comment]
yes they are all installed.


On Thu, Feb 12, 2015 at 12:50 PM, Steven McGrath <notifications@github.com>
wrote:

> is driftnet, ettercap, and tshark installed?
>
> --
> Reply to this email directly or view it on GitHub.
>



-- 
Marc-André Meloche

**Comment by madmantm** [comment]
^Cmadmantm@ubuntu:~$ ettercap


ettercap 0.7.6 copyright 2001-2013 Ettercap Development Team



Please select an User Interface


madmantm@ubuntu:~$ driftnet

Thu Feb 12 09:51:31 2015 [driftnet] error: pcap_lookupdev: no suitable
device found

Thu Feb 12 09:51:31 2015 [driftnet] error: try specifying an interface with
-i

Thu Feb 12 09:51:31 2015 [driftnet] error: or a pcap capture file with -f

madmantm@ubuntu:~$ tshark

tshark: There are no interfaces on which a capture can be done

On Thu, Feb 12, 2015 at 12:51 PM, Marc-Andre Meloche <
marcandremeloche@gmail.com> wrote:

> yes they are all installed.
>
>
> On Thu, Feb 12, 2015 at 12:50 PM, Steven McGrath <notifications@github.com
> > wrote:
>
>> is driftnet, ettercap, and tshark installed?
>>
>> --
>> Reply to this email directly or view it on GitHub.
>>
>
>
>
> --
> Marc-André Meloche
>



-- 
Marc-André Meloche

**Comment by SteveMcGrath** [comment]
take a look at the commands that are being run in the settings page and try to replicate the error.  basically the driftnet process is not starting up for some reason (or exiting abnormally)

**Comment by madmantm** [comment]
Yeah, i tried them all and they work, normally intercepting packets.


On Thu, Feb 12, 2015 at 12:53 PM, Steven McGrath <notifications@github.com>
wrote:

> take a look at the commands that are being run in the settings page and
> try to replicate the error. basically the driftnet process is not starting
> up for some reason (or exiting abnormally)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveMcGrath/DoFler/issues/6#issuecomment-74118273>.
>



-- 
Marc-André Meloche

**Comment by madmantm** [comment]
is it possible to run all commands manually and feed it to them main web interface?

**Comment by madmantm** [comment]
i tried the fedora install guide, and i have the same issue.

Both Ubuntu and Fedora are giving me the same issue.

 "python-requests/2.5.0 CPython/2.7.8 Linux/3.17.4-301.fc21.x86_64"
Process driftnet:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/dofler/parsers/base.py", line 37, in run
    self.realtime_process()
  File "/usr/lib/python2.7/site-packages/dofler/parsers/base.py", line 55, in realtime_process
    self.p = pexpect.spawn(self.command)
  File "/usr/lib/python2.7/site-packages/pexpect/__init__.py", line 493, in __init__
    fd = sys.__stdin__.fileno()
ValueError: I/O operation on closed file


 "python-requests/2.5.0 CPython/2.7.8 Linux/3.17.4-301.fc21.x86_64"
Process ettercap:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/dofler/parsers/base.py", line 37, in run
    self.realtime_process()
  File "/usr/lib/python2.7/site-packages/dofler/parsers/base.py", line 55, in realtime_process
    self.p = pexpect.spawn(self.command)
  File "/usr/lib/python2.7/site-packages/pexpect/__init__.py", line 493, in __init__
    fd = sys.__stdin__.fileno()
ValueError: I/O operation on closed file


 "python-requests/2.5.0 CPython/2.7.8 Linux/3.17.4-301.fc21.x86_64"
Process tshark:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/dofler/parsers/base.py", line 37, in run
    self.realtime_process()
  File "/usr/lib/python2.7/site-packages/dofler/parsers/base.py", line 55, in realtime_process
    self.p = pexpect.spawn(self.command)
  File "/usr/lib/python2.7/site-packages/pexpect/__init__.py", line 493, in __init__
    fd = sys.__stdin__.fileno()
ValueError: I/O operation on closed file

**Comment by HoLyVieR** [comment]
The issue can be reproduced by using the latest version of the library pexpect (version 3.3). There are other version of pexpect which aren't problematic and can be used in the meantime as a workaround. From my test pexpect 3.1 is working fine.

Workaround:
    pip uninstall pexpect
    pip install pexpect==3.1

To reproduce:
    pip install pexpect --upgrade

**Comment by SteveMcGrath** [comment]
I am now forcing the use of pexpect 3.1 in the setup.py file.  This issue should no longer show up.  Thanks for the effort in tracing down the root issue!
